services:
  trakx:
    build: .
    container_name: trakx
    ports:
      - "1337:1337"
      - "1337:1337/udp"
    restart: unless-stopped
    volumes:
      - trakx-config:/home/trakx/.config/trakx
      - trakx-cache:/home/trakx/.cache/trakx
    environment:
      - TRAKX_LOGLEVEL=info

volumes:
  trakx-config:
  trakx-cache:
