# Trakx YAML configuration.
# Values can be overridden using environment variables.
# For example: `TRAKX_LOGLEVEL=debug trakx execute`

# Log level. "debug", "info", "warn", or "error".
loglevel: info

# Cache is the directory in which trakx will write it's PID, logs, and database
# backup files. Leave blank for default of XDG_CACHE_HOME/trakx
cache:

# Trakx can track statistic such as the number of announces, seeds, unique ips, etc.
# They are published via go's expvar standard at '/stats'.
stats:
  # Enable general stats collection. Low memory and performance impact.
  general: true

  # Enable unique IP addresses calculation. High memory and performance impact.
  ip: false

  # How often to update expvar values.
  interval: 1s

debug:
  # Port to serve pprof on. Leave blank to disable pprof.
  # Do not enable in prod - pprof can be used to dump memory.
  pprof:

# Announce interval = `base + [0, fuzz]`. Fuzz is useful to spread out traffic
# after tracker is started.
announce:
  base: 30m
  fuzz: 5m

http:
  # Enables the http tracker. If you wish to serve files and/or expvar
  # stats without running the http tracker you may set this to false and
  # set `port` and `serve`.
  tracker: true

  # Port to bind. Leave blank to fully disable HTTP server.
  port: 1337
  
  # IP address to bind. Leave blank for all interfaces.
  ip: 
  
  # Number of worker goroutines. Leave blank for sensible default based on cores.
  routines:

  # TCP timeouts starting from connection establishment.
  timeout:
    read: 5s
    write: 8s

  # Optional path to serve files from. Note that the web server component of
  # the tracker is not fully HTTP compliant and only serves basic static pages.
  # If you wish to serve a complex website with the tracker enabled a reverse proxy
  # is recommended. Pass `/announce`, `/scrape`, `/heartbeat`, and optionally `/stats`
  # to Trakx.
  serve: 

udp:
  # Port to bind. Leave blank to disable UDP tracker.
  port: 1337
  
  # IP address to bind. Leave blank for all interfaces.
  ip: 
  
  # Number of worker goroutines. Leave blank for sensible default based on cores.
  routines:

  connections:
    # Validate connection IDs. WARNING: tracker can be abused for UDP amplifcation
    # attacks if disabled. Only disable on trusted networks.
    validate: true

    # How often to garbage collect the connection cache for expired connections.
    gc: 10m

    # Maximum connection age before garbage collection.
    expiry: 30m

numwant:
  # Default number of peers in response if numwant is unspeficied.
  default: 50
  
  # Maximum number of peers in response. Numwant above this will be capped.
  limit: 200

db:
  # How often to garbage collect the database for expired peers.
  gc: 10m
  
  # Maximum peer age before garbage collection. Is is recommended that
  # expiry >= announce_base + announce_fuzz to ensure peers dont expire prior to
  # re-announcement. Leave blank for sensible default of
  # `announce_base + announce_fuzz + 5m`.
  expiry:

  backup:
    # Database backup interval. Leave blank to disable backups on interval.
    interval: 300s
  
    # Combined backup snapshot file path. Leave blank for default of `$cache/db`
    path:
