# Trakx alarms

# badges
alarm: trakx_requests
      on: go_expvar_Trakx.requests
  lookup: average -1s of requests_hits
   units: requests
   every: 1s

alarm: trakx_connects
      on: go_expvar_Trakx.requests
  lookup: average -1s of requests_connects
   units: requests
   every: 1s

alarm: trakx_announces
      on: go_expvar_Trakx.requests
  lookup: average -1s of requests_announces
   units: requests
   every: 1s

alarm: trakx_scrapes
      on: go_expvar_Trakx.requests
  lookup: average -1s of requests_scrapes
   units: requests
   every: 1s

alarm: trakx_peers
      on: go_expvar_Trakx.database
  lookup: average -1s of database_peers
   units: peers
   every: 1s

alarm: trakx_ips
      on: go_expvar_Trakx.database
  lookup: average -1s of database_ips
   units: ips
   every: 1s

alarm: trakx_hashes
      on: go_expvar_Trakx.database
  lookup: average -1s of database_hashes
   units: hashes
   every: 1s

alarm: trakx_errors
      on: go_expvar_Trakx.requests
  lookup: incremental-sum -1s of requests_errors
   units: errors/s
   every: 1s
 